#!/usr/bin/env node
// Generates src/styles/fonts.css from the static TrueType weights shipped by
// the `geist` npm package. Regenerated on every build (see package.json's
// "build:fonts" script) — never hand-edit the output file.
//
// Why self-host at all: Chromium's PDF export (used by resuml/Playwright to
// print the CV) embeds CFF/PostScript-outline fonts (.otf) as Type3 — one
// throwaway sub-font per handful of glyphs. Apple's PDFKit (Preview.app
// copy/paste) can't reliably reconstruct word boundaries from that
// structure and inserts phantom spaces mid-word ("decoupled" -> "decou
// pled", "SIL" -> "S IL"), even though nothing is visibly wrong on the
// page. TrueType (glyf-outline) fonts embed as a proper /Type0 CID font
// instead, which PDFKit handles correctly.
//
// Why not just reference "Geist" by family name and let the OS resolve it:
// that only works if the exact right font is installed, unambiguously,
// wherever the PDF gets built (broken in practice — see this repo's fix
// commit). Embedding the font bytes removes that dependency entirely.
//
// Vercel's `geist` package ships static (non-variable) .ttf files with glyf
// outlines directly, so no font-instancing step is needed here.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

// `geist`'s package.json restricts its `exports` map to a couple of entry
// points, none of which expose `dist/fonts`, so resolve the package
// directory directly rather than via require.resolve().
const geistDir = join(dirname(fileURLToPath(import.meta.url)), '../node_modules/geist')

const OUT_FILE = join(dirname(fileURLToPath(import.meta.url)), '../src/styles/fonts.css')

const WEIGHTS = [
  ['Geist', 400, 'geist-sans/Geist-Regular.ttf'],
  ['Geist', 500, 'geist-sans/Geist-Medium.ttf'],
  ['Geist', 600, 'geist-sans/Geist-SemiBold.ttf'],
  ['Geist', 700, 'geist-sans/Geist-Bold.ttf'],
  ['Geist Mono', 400, 'geist-mono/GeistMono-Regular.ttf'],
  ['Geist Mono', 500, 'geist-mono/GeistMono-Medium.ttf'],
  ['Geist Mono', 600, 'geist-mono/GeistMono-SemiBold.ttf'],
  ['Geist Mono', 700, 'geist-mono/GeistMono-Bold.ttf'],
]

const rules = WEIGHTS.map(([family, weight, relPath]) => {
  const bytes = readFileSync(join(geistDir, 'dist/fonts', relPath))
  const base64 = bytes.toString('base64')
  return `@font-face {
  font-family: "${family}";
  font-style: normal;
  font-weight: ${weight};
  font-display: block;
  src: url(data:font/ttf;base64,${base64}) format("truetype");
}`
})

const header = `/*
 * GENERATED by scripts/build-fonts.mjs from the "geist" npm package (see
 * that script for why these fonts are self-hosted and base64-embedded
 * rather than referenced by family name). Do not hand-edit; re-run
 * \`bun run build:fonts\` after updating the "geist" dependency.
 */`

writeFileSync(OUT_FILE, `${header}\n\n${rules.join('\n\n')}\n`)
